# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('Income Account', 'Income Account'), ('Owner Account', 'Owner Account')], max_length=100, null=True)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_bhatta', to='common.Bhatta')),
            ],
        ),
    ]
