# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('batta_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_payment_type', models.CharField(blank=True, choices=[('Credit Ledger Book', 'Credit Ledger Book'), ('Debit Ledger Book', 'Debit Ledger Book')], max_length=100, null=True)),
                ('income_credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('income_debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('income_details', models.CharField(blank=True, max_length=200, null=True)),
                ('income_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_ledger', to='batta_account.Account')),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_bhatta', to='common.Bhatta')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_seasion', to='common.Season')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_payment_type', models.CharField(blank=True, choices=[('Credit Ledger Book', 'Credit Ledger Book'), ('Debit Ledger Book', 'Debit Ledger Book')], max_length=100, null=True)),
                ('owner_credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('owner_debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('owner_details', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_ledger', to='batta_account.Account')),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_bhatta', to='common.Bhatta')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_seasion', to='common.Season')),
            ],
        ),
    ]
