# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('transport', models.CharField(blank=True, max_length=50, null=True)),
                ('carriage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('amount_per_carriage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=65, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('item_quantities', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('expense_item_quantities', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_type', models.CharField(blank=True, choices=[('Inside', 'Inside'), ('Outside', 'Outside')], default='Inside', max_length=100, null=True)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='should be filled automatically if availability type is outside', max_digits=100, null=True)),
                ('estimate_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Multiplication of stock quantity and estimate price', max_digits=100, null=True)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bhatta_income', to='common.Bhatta')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_income', to='common.Season')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_stock', to='common.Season')),
            ],
        ),
    ]
