# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batta_expense', '0001_initial'),
        ('common', '0001_initial'),
        ('batta_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalincome',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_stock', to='batta_stock.Stock'),
        ),
        migrations.AddField(
            model_name='seasonalexpenditure',
            name='bhatta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bhatta_expenditures', to='common.Bhatta'),
        ),
        migrations.AddField(
            model_name='seasonalexpenditure',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_expenditure', to='common.Season'),
        ),
        migrations.AddField(
            model_name='expenditureamount',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_expense', to='batta_expense.SeasonalExpenditure'),
        ),
        migrations.AddField(
            model_name='coalexpense',
            name='bhatta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bhatta_expense', to='common.Bhatta'),
        ),
        migrations.AddField(
            model_name='coalexpense',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_expense', to='common.Season'),
        ),
    ]
