# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-31 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_expense', '0002_auto_20211226_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalexpense',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True),
        ),
    ]
