# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_status',
            field=models.CharField(blank=True, choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=100, null=True),
        ),
    ]
