# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-02-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='ledger_type',
            field=models.CharField(blank=True, choices=[('Ledger Book', 'Ledger Book')], max_length=100, null=True),
        ),
    ]
