# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-02-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batta_customers', '0002_customerledger_ledger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='dated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
