# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-03-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_customers', '0003_customerledger_dated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='khata_count',
            field=models.BooleanField(default=False),
        ),
    ]
