# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-03-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_customers', '0004_customer_khata_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_count',
            field=models.BooleanField(default=False),
        ),
    ]
