# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_customers', '0006_customer_deactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=100, null=True),
        ),
    ]
