# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-09 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expense_type', models.CharField(blank=True, choices=[('diesel', 'diesel')], max_length=100, null=True)),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_bhatta', to='common.Bhatta')),
            ],
        ),
    ]
