# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('other_expense', '0003_auto_20220611_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='MittiLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitti_debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('amount_per_load', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_load', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('mitti_details', models.CharField(blank=True, max_length=200, null=True)),
                ('mitti_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitti_bhatta', to='common.Bhatta')),
                ('other_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitti_ledger', to='other_expense.OtherExpense')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitti_seasion', to='common.Season')),
            ],
        ),
    ]
