# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_expense', '0005_dieselledger_diesel_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mittiledger',
            name='mitti_payment_type',
            field=models.CharField(blank=True, choices=[('Credit Ledger Book', 'Credit Ledger Book'), ('Debit Ledger Book', 'Debit Ledger Book')], max_length=100, null=True),
        ),
    ]
