# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-06-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_expense', '0006_mittiledger_mitti_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
