# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('batta_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=200, null=True)),
                ('transport', models.CharField(blank=True, max_length=200, null=True)),
                ('total_quantity', models.CharField(blank=True, default=1, max_length=10, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('remaining_payment', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bhatta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhatta_invoice', to='common.Bhatta')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='batta_customers.Customer')),
            ],
        ),
    ]
