# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_type', models.CharField(blank=True, choices=[('Salary Staff', 'Salary Staff'), ('Weekly Staff', 'Weekly Staff')], default='Salary Staff', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('expense_count', models.BooleanField(default=False)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staf_bhatta', to='common.Bhatta')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAdvanceCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_bricks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('kharcha_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='The rates for 1000 bricks', max_digits=100, null=True)),
                ('weekly_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dasti payment given by weekly', max_digits=100, null=True)),
                ('net_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_season', to='common.Season')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_advance', to='batta_staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_credit_season', to='common.Season')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_ledger', to='batta_staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLedgerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_debit_season', to='common.Season')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_ledger_payment', to='batta_staff.Staff')),
            ],
        ),
    ]
