# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-02 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('batta_staff', '0002_auto_20220102_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOtherCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_load', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='The rate for 1 load', max_digits=100, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_credit_season', to='common.Season')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_other', to='batta_staff.Staff')),
            ],
        ),
    ]
