# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('batta_staff', '0004_auto_20220102_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOtherDebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_staff_debit_season', to='common.Season')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_debit_payment', to='batta_staff.Staff')),
            ],
        ),
    ]
