# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-05-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_staff', '0005_staffotherdebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_payment_action',
            field=models.CharField(blank=True, choices=[('Jamah', 'Jamah'), ('Banam', 'Banam')], max_length=100, null=True),
        ),
    ]
