# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-12-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batta_sales', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=100, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_invoice', to='batta_sales.Invoice')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_season', to='common.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('b_count', models.BooleanField(default=False)),
                ('awal_count', models.BooleanField(default=False)),
                ('duyam_count', models.BooleanField(default=False)),
                ('bhatta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_bhatta', to='common.Bhatta')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_per_item', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_stock_in', to='common.Season')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockin', to='batta_stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_per_item', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_stock_out', to='common.Season')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockout', to='batta_stock.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='purchasedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchased', to='batta_stock.Stock'),
        ),
    ]
