# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('batta_koylas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoylaLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('transport', models.CharField(blank=True, max_length=50, null=True)),
                ('carriage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('amount_per_carriage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=65, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('koyla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koyla_ledger', to='batta_koylas.Koyla')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koyla_season', to='common.Season')),
            ],
        ),
    ]
