# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batta_koylas', '0002_koylaledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoylaLedgerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('koyla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koyla_ledger_payment', to='batta_koylas.Koyla')),
            ],
        ),
    ]
