# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batta_koylas', '0003_koylaledgerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='koyla',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
